version: 2
references:
  commands:
    install_cwl_runner: &install_cwl_runner
      name: "Install cwl-runner"
      command: "pip install cwltest cwl-runner ruamel.yaml==0.15.97"
    run_test: &run_test
      name: "Run test"
      command: "cwltest --verbose --test test.yml"
jobs:
  build:
    # working_directory: /tmp/cwl_test
    docker:
      - image: python:3.7-buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker machine
          command: |
            base=https://github.com/docker/machine/releases/download/v0.16.0
            curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/usr/local/bin/docker-machine &&
            chmod +x /usr/local/bin/docker-machine
      - run: *install_cwl_runner
      - run: *run_test
