version: 2
references:
  commands:
    install_cwl_runner: &install_cwl_runner
      name: "Install cwl-runner"
      command: "sudo pip install cwltest cwl-runner ruamel.yaml==0.15.97"
    run_test: &run_test
      name: "Run test"
      command: "sudo cwltest --verbose --test test.yml"
jobs:
  build:
    # working_directory: /tmp/cwl_test
    docker:
      - image: python:3.7-buster
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_cwl_runner
      - run: *run_test
